### ISSUE TITLE
feat: fetching data 적용 & 데이터 변환으로 인한 수정

### ISSUE THREAD

**Issue by mrlee323** [wanted-group-4/wanted-group-4-snplab#33]
## ISSUE
- Group: `client`
- Type:  `feature`,
- Detail: 데이터 적용

## TODO
- [x] fetching data 적용
- [x] 다운로드 배열로 인한 오류 수정
- [x] 날짜 기간 검색을 위한 배열 변환 

## Labels
Estimated time: E: `.5h`
Group : `client`,
