### ISSUE TITLE
refactor: 당첨여부 로직 리팩토링

### ISSUE THREAD

**Issue by devmagrfs** [wanted-group-4/wanted-group-4-snplab#42]
## ISSUE
- Group: `client`
- Type: `refactor`
- Detail: 당첨여부를 업데이트 시키는 로직을 리팩토링하기

## TODO
- [x] input을 styled components로 교체
- [x] defaultChecked 를 컴포넌트에 내려진 user props에 담긴 win을 이용해서 체크
- [x] db에 보낼 id 값을 user props로 내려진 id값으로 체크

## Labels
Estimated time: E: `0.5h`
Group : `client`
