### ISSUE TITLE
refactor: User 페이지 폼 리팩토링

### ISSUE THREAD

**Issue by greenish0902** [wanted-group-4/wanted-group-4-snplab#49]
## ISSUE
- Group: `client`
- Type: `refactor`, `css`
- Detail: 유저 페이지 리팩토링

## TODO
- [x] useEffect 사용에서 불필요한 렌더링이 있는지 DevTools로 확인하고 최소화하기
- [x] 상수는 외부 파일로 분리하고 import 해 사용하기
- [x] 타입 확인을 위한 할당이 불필요한 로직이라면 고민하고 줄여보기
- [x] memo, useCallback, useMemo 등의 훅을 사용해 렌더링 최적화

## Labels
Estimated time: E: `3h`
Group : `client`
